### ISSUE TITLE
AIA1600 too dark

### ISSUE THREAD

**Issue by helioshk** [Helioviewer-Project/api#100]
Hi,
The AIA1600 images in (J)helioviewer appear much too dark. It seems to be already the case in the source JPEG2000 image with image information lost that can not be recovered by postprocessing.
Example: 
http://94.130.58.182/temp/AIA1600.jpg
Left is helioviewer, right from the SDO website

**Comment by wafels** [comment]
The corrections available within [aiapy](https://gitlab.com/LMSAL_HUB/aia_hub/aiapy) apply to original FITS data. While it is possible to manipulate these corrections so they apply to the JPEG2000 files there is a more direct method that may work. First, we assume that we can correct the darkness of the images using a simple multiplicative factor _f_. Since the sensitivity of the instrument is decreasing with time, the multiplicative factor is a function of time _t_, _f(t)_. Let us further assume that the instrument had its best sensitivity at the start of its operations.

1. Get one AIA 1600 JPEG2000 every 24 hours.
2. Sum the value of all the pixels in the image - at time _t_ this is _S(t)_.
3. Fit the time series to get a smoother time series _Z(t)_.
4. Pick some early time t0 that represents the "best" sensitivity _Z(t0)_.
5. The multiplication factor is defined as _f(t) = Z(t0)/Z(t)_ .

The multiplication factor _f(t)_ can be calculated once (maybe updated once every 6 months to take account of new data and further instrument degradation) and stored on the server. The multiplication factor can be applied at the same time as the color table.

**Comment by dgarciabriseno** [comment]
After trying out the proposal by wafels, it looks like the correction is going to be a bit more complex. Here's the result of correction on an AIA 1600 image:

Before correction:
![image](https://user-images.githubusercontent.com/94071409/157109814-e8ff7651-bed1-47c3-b749-2934a4283497.png)

After correction:
![image](https://user-images.githubusercontent.com/94071409/157109878-f4120de8-9820-42e7-aab2-ca5abd5b1349.png)

**Comment by dgarciabriseno** [comment]
We gained access to the method that suntoday uses to create the high quality images.
The only setback is that it requires the original fits data. Currently helioviewer simply downloads the jp2 images from LMSAL, which gives us the deteriorated images above. Ideally LMSAL or the JSOC would integrate this into their jp2 pipeline.

Since we have access to do this ourselves, it would be a decent workaround to create our own pipeline at least for AIA 1600 and maybe other wavelengths as well, but I'm hesitant to "recreate the wheel" so to speak.

**Comment by dgarciabriseno** [comment]
This was repaired on LMSAL's side. They are looking into repairing older jp2 images as well, which we'll eventually have to import back into helioviewer. Newer AIA 1600 images are already coming in bright and clear.
![image](https://user-images.githubusercontent.com/94071409/161285538-c0233bef-f5b3-42d1-aa83-904950ac7dbc.png)

**Comment by helioshk** [comment]
Beautiful! Just in time for the X1 flare :)
Thank you very much.

I think it is maybe a bit too bright, as the background is not black. But that can be corrected in the client if desired.
![image](https://user-images.githubusercontent.com/20465551/161294142-854d76a0-6010-447a-8dc6-187108feb4c1.png)
