### ISSUE TITLE
Type of device added to statistics

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/api#244]
It would be interesting to divide the existing statistics page into three categories depending on the type of device that is used, if that is possible. The categories are (broadly) phones, tablets and not phones or tablets.

**Comment by dgarciabriseno** [comment]
Working on this https://github.com/dgarciabriseno/api/tree/device-stats

I have it running on beta. Go to http://localhost:8081/statistics/ and scroll down. The last pie chart on the left shows device breakdown. It's not very interesting yet since we weren't tracking any of that info before so most requests are just "unknown" device.

**Comment by dgarciabriseno** [comment]
This has been implemented
