### ISSUE TITLE
Running difference returns a black image  

### ISSUE THREAD

**Issue by PabloA-dev-coder** [Helioviewer-Project/api#37]
Hello, 

Running difference return a black image.

see:
https://inf-helio-test-api.ias.u-psud.fr/?action=getTile&id=2983848&imageScale=2.42044088&x=-1&y=-1&difference=1&diffCount=60&diffTime=1&baseDiffTime=2018-03-09T15%3A46%3A48.000Z

I have everything up to date from git : api,  helioviewer.org & esajpip-SWHV

Best regards
Pablo 
IAS

**Comment by ebuchlin** [comment]
Hello,
We still have this issue, with the production server:
https://helioviewer-api.ias.u-psud.fr/?action=getTile&id=2983848&imageScale=2.42044088&x=-1&y=-1&difference=1&diffCount=1&diffTime=2
The same getTile arguments on helioviewer.org give a good difference image: 
https://api.helioviewer.org/?action=getTile&id=2983848&imageScale=2.42044088&x=-1&y=-1&difference=1&diffCount=1&diffTime=2
Is there anything we should check server-side?
Best regards,
Eric

**Comment by dgarciabriseno** [comment]
It doesn't look like this is a problem anymore.
https://helioviewer-api.ias.u-psud.fr/?action=getTile&id=2983848&imageScale=2.42044088&x=-1&y=-1&difference=1&diffCount=1&diffTime=2 returns an image, not a black tile.

But the images returned by your mirror is more pixelated... not sure why.
Closing this issue since the API request does not "return a black image."
Please open a new issue if you want to look into the difference with the running differences.

**Comment by ebuchlin** [comment]
Indeed, the server has been upgraded since 2019 and this has solved the "black tile" issue.

About the pixelated image: this seems to be because the images are not the same on both servers for the same Tile id (please compare https://helioviewer-api.ias.u-psud.fr/?action=getTile&id=2983848&imageScale=2.42044088&x=-1&y=-1 and https://api.helioviewer.org/?action=getTile&id=2983848&imageScale=2.42044088&x=-1&y=-1 ). I guess that this is not a real issue.

**Comment by dgarciabriseno** [comment]
👍
