### ISSUE TITLE
Requesting a general search for gaps on the data

### ISSUE THREAD

**Issue by takucera** [Helioviewer-Project/api#52]
Hi, I've had a few cases in which I found that there were hours or days of data missing from the helioviewer database. These were in SDO/AIA and STEREO/EUVI data. The data existed, they just were not in Helioviewer for some reason. It took a fairly long time for the data to be added.
  
I'd like to request that some method for looking for such gaps be developed so that the gaps can be detected and filled automatically.

Terry

**Comment by ebuchlin** [comment]
Hello,
At MEDOC we have done a first pass of gap filling from the GSFC server, using `downloader.py` on the days given by https://git.ias.u-psud.fr/medoc/hvcoverage/-/blob/master/scripts/union_gaps.py . We have gained about 10 millions of files, but we still have some smaller gaps that require a second pass.

I have noted the new coverage API output, but also issue #48 affecting it.

**Comment by wafels** [comment]
@ebuchlin - the scripts you have written, and the plots you made earlier on this year, are very useful.  We should adapt them to create some similar visualizations for the data here at GSFC.

**Comment by wafels** [comment]
@ebuchlin, @takucera - last year we had a student who took the MEDOC scripts for coverage plots and adapted them. We now have daily coverage plots of each data source that can be found here: https://api.helioviewer.org/statistics/bokeh/coverages/ . Note that the data for the plots can take a moment or two to download. We also have histograms of the number of files per day at https://api.helioviewer.org/statistics/bokeh/histograms/ . The histograms are to help understand where data might be missing, but are mission-dependent. It would be useful to know how many files each mission expects to have each day so we could properly determine how many files are missing.

**Comment by ebuchlin** [comment]
Thanks, this looks very good! Is it in some helioviewer.org release? (at some point we will have to consider doing an update on our side)

I guess that the number of expected files per day (and even this quantity might not be sufficient) is not easy to know for missions other than SDO. Even for SDO, there are mission-dependent events (downtimes, eclipses...), glitches in the SDO or HelioViewer pipelines, and each case requires analysis before deciding whether something has to be done to fill the gap. In order not to lose time repeating the analysis, the gaps would have to be tagged in some way.

**Comment by dgarciabriseno** [comment]
@ebuchlin You are right, we're still not sure how to identify mission-dependent events. We are thinking about how to identify these gaps on the data sources themselves. That way we can at least identify if a gap is caused by the mission or by a problem in Helioviewer. But it is difficult to automate when different data sources have different known outages that need to be accounted for. You can check out [this branch on my fork](https://github.com/dgarciabriseno/api/tree/gap-finder) for the gap detection scripts I'm working on.

As for a release, the statistics coverage is available in release 3.3.2. You may also want to cherry-pick 1cb669 from beta, but it's not necessary. It fixes some problems with plot generation I was having on the beta server because some datasets are still empty.

Navigate to `<api repo>/scripts/hv_stats` and execute `sh generate_bokeh_plots.sh`
The generated coverage pages will be created in `<api repo>/docroot/statistics/bokeh`

**Comment by dgarciabriseno** [comment]
See #50 for a continuation of this effort.
