### ISSUE TITLE
Thumbnails do not show for movies spanning observation data

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/api#78]
The attached screenshot shows that movie thumbnails are not displayed when the tab is opened.

![Screen Shot 2021-08-20 at 09 48 24](https://user-images.githubusercontent.com/983575/130243341-dab1a06f-2140-42b8-9ad8-877cd9dd51b4.png)

**Comment by dgarciabriseno** [comment]
It looks like there's a problem with getting URLs into our database, I am considering just deleting the column since we can just auto-generate the thumbnails on-the-fly with the video id.

![image](https://user-images.githubusercontent.com/94071409/148271589-b3cd6933-95e8-411b-a0cb-e4663cc1602c.png)

**Comment by dgarciabriseno** [comment]
Fixed in 3.3.3
